---
-
  become: true
  hosts: gitlab
  become_method: sudo
  become_user: root
  tasks:
  - name: Install postfix
    apt:
      name:
        - postfix
        - curl

  - name: Add gitlab repositories
    shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash

  - name: Install gitlab-ce
    apt:
      name:
        - gitlab-ce

  - name: Edit /etc/gitlab/gitlab.rb
    lineinfile: dest=/etc/gitlab/gitlab.rb
                regexp='^external_url'
                insertbefore=BOF
                line="external_url 'http://gitlab.my'"

  - name: GitLab reconfigure
    shell: gitlab-ctl reconfigure > reconfigure.log
