---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-service
  labels:
     env  : prod
     owner: AlexeySimonov
spec:
  selector:
    project: local-web      # Selecting PODs with those Labels
  ports:
    - protocol  : TCP
      port      : 80
      targetPort: 80
