---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base.local.net
spec:
  rules:
  - host: base.local.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: base
            port:
              number: 80
  ingressClassName: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana.my
spec:
  rules:
  - host: grafana.my
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000

  ingressClassName: nginx
