apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservice
spec:
  rules:
  - host: base.local.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: base
            port:
              number: 80
  ingressClassName: nginx
