---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-base
  labels:
    app : my-web-k8s-base
spec:
  replicas: 2
  selector:
    matchLabels:
      project: local-web-base
  template:
    metadata:
      labels:
        project: local-web-base   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : web-base
          image: simff/ng:base
          ports:
            - containerPort: 80

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web1
  labels:
    app : my-web1-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      project: local-web1
  template:
    metadata:
      labels:
        project: local-web1   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : web1
          image: simff/ng:web1
          ports:
            - containerPort: 80

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web2
  labels:
    app : my-web2-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      project: local-web2
  template:
    metadata:
      labels:
        project: local-web2   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : web2
          image: simff/ng:web2
          ports:
            - containerPort: 80

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web3
  labels:
    app : my-web3-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      project: local-web3
  template:
    metadata:
      labels:
        project: local-web3   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : web3
          image: simff/ng:web3
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-base-service
  labels:
     env  : test-base
     owner: AlexeySimonov
spec:
  selector:
    project: local-web-base      # Selecting PODs with those Labels
  ports:
    - protocol  : TCP
      port      : 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-web1-service
  labels:
     env  : test-web1
     owner: AlexeySimonov
spec:
  selector:
    project: local-web1      # Selecting PODs with those Labels
  ports:
    - protocol  : TCP
      port      : 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-web2-service
  labels:
     env  : test-web2
     owner: AlexeySimonov
spec:
  selector:
    project: local-web2      # Selecting PODs with those Labels
  ports:
    - protocol  : TCP
      port      : 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-web3-service
  labels:
     env  : test-web3
     owner: AlexeySimonov
spec:
  selector:
    project: local-web3      # Selecting PODs with those Labels
  ports:
    - protocol  : TCP
      port      : 80
      targetPort: 80
