---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 123qwe

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app : my-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      project: local-postgres
  template:
    metadata:
      labels:
        project: local-postgres   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: files-psql

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
     env  : postgres
     owner: AlexeySimonov
spec:
  selector:
    project: local-postgres      # Selecting PODs with those Labels
  ports:
   - port: 5432
  selector:
   app: postgres
