---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs-share
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.210
    path: /opt/grafana

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: files-grafana
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    
