---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rabbit
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbit
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbit
  nfs:
    server: 192.168.1.210
    path: /mnt/rmq

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-rabbit
  namespace: rabbitmq
spec:
  storageClassName: rabbit
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
