---
-
  become: true
  hosts: nodes
  become_method: sudo
  become_user: root
  tasks:
#  - name: Update APT
#    apt:
#      update_cache: yes

  - name: Install haproxy
    apt:
      name:
      - haproxy

  - name: Set net.ipv4.ip_nonlocal_bind in sysctl
    become: yes
    sysctl:
      name: net.ipv4.ip_nonlocal_bind
      value: '1'
      state: present
      reload: yes

  - name: Edit /etc/netplan/00-installer-config.yaml
    lineinfile:
      path: /etc/netplan/00-installer-config.yaml
      insertafter: "^      - {{ansible_host}}"
      line: "      - {{hostvars['haproxy'].ansible_host}}/24"

  - name: Restart netplan
    shell: netplan apply

  - name: Change /etc/haproxy/haproxy.cfg
    copy:
      dest: "/etc/haproxy/haproxy.cfg"
      content: |
        global
          maxconn 100
          log     127.0.0.1 local2
        defaults
          log global
          mode tcp
          retries 2
          timeout client 30m
          timeout connect 4s
          timeout server 30m
          timeout check 5s
        listen stats
          mode http
          bind *:8080
          stats enable
          stats uri /
        listen postgres
          bind *:5430
          option httpchk
          http-check expect status 200
          default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
          server {{ hostvars['p1'].inventory_hostname }} {{ hostvars['p1'].ansible_host }}:5432 maxconn 100 check port 8008
          server {{ hostvars['p2'].inventory_hostname }} {{ hostvars['p2'].ansible_host }}:5432 maxconn 100 check port 8008
          server {{ hostvars['p3'].inventory_hostname }} {{ hostvars['p3'].ansible_host }}:5432 maxconn 100 check port 8008


  - name: Restart haproxy
    service:
      name: "haproxy"
      state: "restarted"
      enabled: "yes"

#  - name: Unconditionally reboot the machine with all defaults
#    ansible.builtin.reboot:
