---
-
  become: true
  hosts: nodes
  become_method: sudo
  become_user: root
  tasks:
  - name: Update APT
    apt:
      update_cache: yes

  - name: Install postgresql
    apt:
      name:
        - postgresql
        - postgresql-contrib

  - name: Stop postgresql
    service:
      name: "postgresql"
      state: "stopped"
      enabled: "yes"

  - name: Check postgresql version
    ansible.builtin.shell: ls /usr/lib/postgresql/
    register: psql_ver

  - name: Print
    debug:
      msg: "{{psql_ver.stdout}}"

  - name: Link files
    shell: ln -s /usr/lib/postgresql/{{psql_ver.stdout}}/bin/* /usr/sbin/
    ignore_errors: yes
