---
-
  become: true
  hosts: worknode01,worknode02
  become_method: sudo
  become_user: root
  tasks:
  - name: Creates directory /mirror
    file:
      mode: "0777"
      path: /mirror
      state: directory

#  - name: Add host /etc/hosts
#    copy:
#      dest: "/etc/hosts"
#      content: |
#        127.0.0.1 localhost
#        {{ hostvars['worknode01'].ansible_host }} {{ hostvars['worknode01'].inventory_hostname }}
#        {{ hostvars['worknode02'].ansible_host }} {{ hostvars['worknode02'].inventory_hostname }}

  - name: Add script /root/mk-sdb1.sh
    copy:
      dest: "/root/mk-sdb1.sh"
      mode: "0777"
      content: |
        #!/bin/bash
        echo -e "n\np\n1\n\n\nw" | fdisk /dev/sdb

  - name: Make /dev/sdb1
    shell: ./mk-sdb1.sh

  - name: Update APT
    apt:
      update_cache: yes

  - name: Install packeges
    apt:
      name:
        - drbd-utils
        - nfs-kernel-server
        - nfs-common
        - heartbeat
    ignore_errors: true

  - name: Add config /etc/drbd.conf
    copy:
      dest: "/etc/drbd.conf"
      content: |
        global { usage-count no; }
        common { syncer { rate 1023M; } }
        resource r0 {
                protocol C;
                startup {
                        wfc-timeout  15;
                        degr-wfc-timeout 60;
                }
                net {
                        cram-hmac-alg sha1;
                        shared-secret "secret";
                }
                on worknode01 {
                        device /dev/drbd0;
                        disk /dev/sdb1;
                        address {{ hostvars['worknode01'].ansible_host }}:7788;
                        meta-disk internal;
                }
                on worknode02 {
                        device /dev/drbd0;
                        disk /dev/sdb1;
                        address {{ hostvars['worknode02'].ansible_host }}:7788;
                        meta-disk internal;
                }
        }

  - name: drbdadm create-md r0
    shell: drbdadm create-md r0

  - name: systemctl enable drbd
    shell: systemctl enable drbd

  - name: Restart drbd
    service:
      name: "drbd"
      state: "restarted"
      enabled: "yes"

-
  become: true
  hosts: worknode01
  become_method: sudo
  become_user: root
  tasks:
  - name: Create script /root/activate-mirror.sh
    copy:
      dest: "/root/activate-mirror.sh"
      mode: "0777"
      content: |
        #!/bin/bash
        drbdadm -- --overwrite-data-of-peer primary all
        sleep 60
        mkfs.xfs /dev/drbd0
        mount /dev/drbd0 /mirror
        touch /mirror/test-file

  - name: Activate-mirror
    shell: ./activate-mirror.sh

-
  become: true
  hosts: worknode02
  become_method: sudo
  become_user: root
  tasks:
  - name: drbdadm secondary
    shell: drbdadm secondary r0

-
  become: true
  hosts: worknode01,worknode02
  become_method: sudo
  become_user: root
  tasks:
  - name: Create remove-init.sh
    copy:
      dest: "/root/remove-init.sh"
      mode: "0777"
      content: |
        #!/bin/bash
        update-rc.d -f nfs-kernel-server remove
        update-rc.d -f nfs-common remove
        update-rc.d nfs-kernel-server stop 20 0 1 2 3 4 5 6 .
        update-rc.d nfs-common  stop 20 0 1 2 3 4 5 6 .

  - name: Remove the runlevel init scripts
    shell: ./remove-init.sh

-
  become: true
  hosts: worknode01
  become_method: sudo
  become_user: root
  tasks:
  - name: Create script /root/configure-exports.sh
    copy:
      dest: "/root/configure-exports.sh"
      mode: "0777"
      content: |
        #!/bin/bash
        mv /var/lib/nfs/ /mirror
        ln -s /mirror/nfs/ /var/lib/nfs
        mv /etc/exports /mirror
        ln -s /mirror/exports /etc/exports

  - name: Configure-exports
    shell: ./configure-exports.sh

  - name: Creates directory /mirror/export
    file:
      mode: "0777"
      path: /mirror/export
      state: directory

  - name: Add nfs sharing to /mirror/exports
    lineinfile:
      dest: /mirror/exports
      line: "/mirror/export        {{shared}}(rw,no_subtree_check)"
      state: present
      insertafter: EOF
      create: True

  - name: Exportfs
    shell: exportfs -a
-
  become: true
  hosts: worknode02
  become_method: sudo
  become_user: root
  tasks:
  - name: Create script /root/configure-exports.sh
    copy:
      dest: "/root/configure-exports.sh"
      mode: "0777"
      content: |
        #!/bin/bash
        rm -rf /var/lib/nfs
        ln -s /mirror/nfs/ /var/lib/nfs
        rm /etc/exports
        ln -s /mirror/exports /etc/exports

  - name: Configure-exports
    shell: ./configure-exports.sh

-
  become: true
  hosts: worknode01,worknode02
  become_method: sudo
  become_user: root
  tasks:
  - name: Create /etc/heartbeat/ha.cf
    copy:
      dest: "/etc/heartbeat/ha.cf"
      content: |
        logfacility     local0
        keepalive 2
        deadtime 30
        warntime 10
        initdead 120
        bcast ens33
        node {{ hostvars['worknode01'].inventory_hostname }}
        node {{ hostvars['worknode02'].inventory_hostname }}

  - name: Create /etc/heartbeat/authkeys
    copy:
      mode: "0600"
      dest: "/etc/heartbeat/authkeys"
      content: |
        auth 3
        3 md5 password

  - name: Create /etc/heartbeat/haresources
    copy:
      dest: "/etc/heartbeat/haresources"
      content: |
        worknode01 IPaddr::{{virtip}} drbddisk::r0 Filesystem::/dev/drbd0::/mirror::xfs nfs-kernel-server

  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot:

-
  become: true
  hosts: master01,master02
  become_method: sudo
  become_user: root
  tasks:
  - name: Update APT
    apt:
      update_cache: yes

  - name: Install packeges
    apt:
      name:
        - nfs-common
