---
-
  become: true
  hosts: master02,master03
  become_method: sudo
  become_user: root
  tasks:
  - name: Change /etc/environment
    ansible.builtin.blockinfile:
      path: /etc/environment
      block: |
        KUBECONFIG=/etc/kubernetes/admin.conf
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: Kube-Init-Masters
    shell: kubeadm init --config=kube-init.yaml

  - name: Waiting for 2 minutes until the masters ready
    pause:
      minutes: 2
