---
-
  become: true
  hosts: masters,worknodes
  become_method: sudo
  become_user: root
  tasks:
  - name: Changes /etc/modules-load.d/modules.conf
    copy:
      dest: "/etc/modules-load.d/modules.conf"
      content: |
        overlay
        br_netfilter

  - name: Apply modules
    shell: modprobe overlay && modprobe br_netfilter

  - name: Creating /etc/sysctl.d/kubernetes.conf
    copy:
      dest: "/etc/sysctl.d/kubernetes.conf"
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1

  - name: Apply system changes
    shell: sysctl --system
