---
-
  become: true
  hosts: masters,worknodes
  become_method: sudo
  become_user: root
  tasks:
  - name: Containerd 1
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg

  - name: Containerd 2
    shell: echo -ne '\n' | add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

  - name: Update APT
    apt:
      update_cache: yes

  - name: Install packages
    apt:
      name:
        - containerd.io

  - name: Containerd 3
    shell: containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1

  - name: Containerd 4
    shell: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

  - name: Restart Containerd
    service:
      name: "containerd"
      daemon_reload: true
      state: "restarted"
      enabled: "yes"
