# mkdir /opt/data/grafana
# chmod 0777 /opt/data/grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ hostvars['master'].ansible_host }}
    path: /opt/data/grafana

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: files-grafana
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app : my-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      project: local-grafana
  template:
    metadata:
      labels:
        project: local-grafana   # Service will look for those PODS Labels!!!
    spec:
      containers:
      - image: grafana/grafana
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
           claimName: files-grafana


---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
     env  : grafana
     owner: AlexeySimonov
spec:
  selector:
    project: local-grafana      # Selecting PODs with those Labels
  ports:
    - protocol  : TCP
      port      : 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
spec:
  rules:
  - host: kube-grafana.my
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000

  ingressClassName: nginx

# 9614 Dashboard
