---
-
  become: true
  hosts: all
  become_method: sudo
  become_user: root
  tasks:
  - name: Creating /opt/kafka/config/server.properties
    copy:
      owner: kafka
      group: kafka
      dest: "/opt/kafka/config/server.properties"
      content: |
        broker.id={{id}}
        delete.topic.enable=true
        num.network.threads=3
        num.io.threads=8
        socket.send.buffer.bytes=102400
        socket.receive.buffer.bytes=102400
        socket.request.max.bytes=104857600
        log.dirs=/tmp/kafka-logs-1
        num.partitions=1
        num.recovery.threads.per.data.dir=1
        default.replication.factor=3
        offsets.topic.replication.factor={{offsets}}
        transaction.state.log.replication.factor=3
        transaction.state.log.min.isr=2
        min.insync.replicas=2
        acks=all
        log.retention.hours=168
        log.segment.bytes=1073741824
        log.retention.check.interval.ms=300000
        zookeeper.connect={{ hostvars['kafka01'].ansible_host }}:2181, {{ hostvars['kafka02'].ansible_host }}:2181, {{ hostvars['kafka03'].ansible_host }}:2181
        zookeeper.connection.timeout.ms=18000
        group.initial.rebalance.delay.ms=0

  - name: Creating /etc/systemd/system/kafka.service
    copy:
      dest: "/etc/systemd/system/kafka.service"
      content: |
        [Unit]
        Description=Kafka Service
        Requires=zookeeper.service
        After=zookeeper.service
        [Service]
        Type=idle
        User=kafka
        ExecStart=/bin/sh -c '/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties > /opt/kafka/kafka.log 2>&1'
        ExecStop=/opt/kafka/bin/kafka-server-stop.sh
        ExecReload=/bin/kill -HUP $MAINPID
        Restart=on-failure
        [Install]
        WantedBy=multi-user.target

  - name: daemon-reload
    shell: systemctl daemon-reload

  - name: systemctl enable kafka
    shell: systemctl enable kafka

  - name: Restart kafka
    service:
      name: "kafka"
      state: "restarted"
      enabled: "yes"
