---
-
  become: true
  hosts: p1
  become_method: sudo
  become_user: root
  tasks:
#  - name: Edit /etc/netplan/00-installer-config.yaml
#    ansible.builtin.lineinfile:
#      path: '/etc/netplan/00-installer-config.yaml'
#      insertafter: '^192.168.1.'
#      line: '      - 192.168.1.220/24'

  - name: Edit /etc/netplan/00-installer-config.yaml
    lineinfile:
      path: /etc/netplan/00-installer-config.yaml
      insertafter: "^      addresses:"
      line: "      - {{hostvars['haproxy'].ansible_host}}/24"
#  - name: Restart netplan
#    shell: netplan apply
